// PromptLab - Complete Database of 70+ World-Class AI Prompts
// All prompts are professionally curated and tested

const allPromptsDatabase = [
    // MARKETING (10 prompts) - IDs 1-10
    {id:1,title:'SEO Blog Post Generator',category:'marketing',text:'You are an SEO expert. Create comprehensive SEO-optimized blog post about [TOPIC]. Include: compelling title with primary keyword, meta description (150-160 chars), H2/H3 subheadings, 1500+ words valuable content, internal/external links, FAQ section, call-to-action. Optimize for search intent and readability.',rating:4.9,uses:15200,submitter:'Curated',type:'curated',tags:['seo','content','blog']},
    {id:2,title:'Social Media Campaign Planner',category:'marketing',text:'Create 30-day social media campaign for [PRODUCT/SERVICE]. Include: campaign strategy, content calendar (30 days), post types, captions with hashtags, visual concepts, posting schedule, engagement tactics, paid ad recommendations, KPIs.',rating:4.8,uses:8900,submitter:'Curated',type:'curated',tags:['social-media','campaign']},
    {id:3,title:'Email Marketing Sequence',category:'marketing',text:'Design high-converting email sequence for [PRODUCT/SERVICE]. Create 5-7 emails with subject lines (A/B variants), body copy, CTAs, optimal send times, personalization tokens, expected metrics.',rating:4.7,uses:6700,submitter:'Curated',type:'curated',tags:['email-marketing','conversion']},
    {id:4,title:'Landing Page Copy Optimizer',category:'marketing',text:'Create high-converting landing page copy for [PRODUCT]. Include: hero section (headline, subheadline, CTA), problem agitation, solution presentation, social proof, feature breakdown, objection handling FAQ, final CTA section with urgency.',rating:4.9,uses:11400,submitter:'Curated',type:'curated',tags:['landing-page','copywriting','conversion']},
    {id:5,title:'Google Ads Campaign Structure',category:'marketing',text:'Design comprehensive Google Ads campaign for [PRODUCT]. Include: campaign structure, ad groups (3-5), keyword research (20-30 keywords), ad copy (3 variants), extensions, landing page alignment, conversion tracking, performance benchmarks.',rating:4.8,uses:7200,submitter:'Curated',type:'curated',tags:['google-ads','ppc','sem']},
    {id:6,title:'Content Marketing Strategy',category:'marketing',text:'Develop 90-day content marketing strategy for [COMPANY]. Include: content pillars (3-5), content mix strategy, editorial calendar, SEO integration, distribution plan, repurposing strategy, metrics & KPIs.',rating:4.9,uses:9800,submitter:'Curated',type:'curated',tags:['content-strategy','marketing','seo']},
    {id:7,title:'Product Launch Marketing Plan',category:'marketing',text:'Create product launch marketing plan for [PRODUCT]. Include: pre-launch (4-6 weeks), launch week day-by-day plan, post-launch (4 weeks), channels & tactics, messaging framework, budget allocation, success metrics.',rating:4.8,uses:5600,submitter:'Curated',type:'curated',tags:['product-launch','go-to-market']},
    {id:8,title:'Brand Voice & Messaging Guide',category:'marketing',text:'Create comprehensive brand voice guide for [COMPANY]. Include: brand personality, voice attributes, messaging pillars, audience-specific messaging, vocabulary guidelines, channel adaptations, examples & templates.',rating:4.7,uses:4900,submitter:'Curated',type:'curated',tags:['brand-voice','messaging','copywriting']},
    {id:9,title:'Competitor Analysis Report',category:'marketing',text:'Conduct comprehensive competitor analysis for [YOUR COMPANY]. Analyze 3-5 competitors: company overview, product/service analysis, marketing strategy, website analysis, customer perception, SWOT analysis, strategic recommendations.',rating:4.8,uses:7800,submitter:'Curated',type:'curated',tags:['competitor-analysis','market-research','strategy']},
    {id:10,title:'Influencer Marketing Campaign',category:'marketing',text:'Design influencer marketing campaign for [PRODUCT]. Include: influencer strategy, 20 potential influencers list, campaign brief, compensation structure, content requirements, tracking & measurement, outreach templates.',rating:4.7,uses:6100,submitter:'Curated',type:'curated',tags:['influencer-marketing','social-media','campaign']},

    // CODING (12 prompts) - IDs 11-22
    {id:11,title:'Python Code Review & Optimization',category:'coding',text:'You are a senior Python developer. Review this code: [CODE]. Provide: code quality assessment, performance optimization, best practices (PEP 8), security considerations, testing recommendations, refactored version with comparisons, documentation improvements.',rating:4.9,uses:12300,submitter:'Curated',type:'curated',tags:['python','code-review','optimization']},
    {id:12,title:'React Component Architecture',category:'coding',text:'Design scalable React architecture for [FEATURE]. Include: component hierarchy, state management strategy, component patterns, performance optimization, TypeScript types, testing strategy, sample implementation.',rating:4.8,uses:8900,submitter:'Curated',type:'curated',tags:['react','javascript','architecture','frontend']},
    {id:13,title:'SQL Query Optimization',category:'coding',text:'Optimize this SQL query: [QUERY]. Provide: query analysis, execution plan breakdown, optimized query, indexing recommendations, schema improvements, before/after metrics, monitoring approach.',rating:4.9,uses:7600,submitter:'Curated',type:'curated',tags:['sql','database','optimization','performance']},
    {id:14,title:'API Design & Documentation',category:'coding',text:'Design RESTful API for [APPLICATION]. Include: endpoint design, request/response formats, pagination, filtering/sorting, error handling, rate limiting, authentication, OpenAPI/Swagger spec, SDK examples.',rating:4.8,uses:9200,submitter:'Curated',type:'curated',tags:['api','rest','backend','documentation']},
    {id:15,title:'Debugging Strategy Generator',category:'coding',text:'Debug this issue: [BUG DESCRIPTION]. Provide: hypothesis generation (5 likely causes), systematic debugging plan, diagnostic commands, isolation techniques, temporary workarounds, preventive measures, root cause analysis framework.',rating:4.7,uses:5800,submitter:'Curated',type:'curated',tags:['debugging','troubleshooting','problem-solving']},
    {id:16,title:'Docker & DevOps Setup',category:'coding',text:'Create Docker and CI/CD setup for [APPLICATION]. Include: Dockerfile (multi-stage), docker-compose.yml, CI/CD pipeline (GitHub Actions), Kubernetes manifests, nginx configuration, environment management, monitoring & logging.',rating:4.9,uses:11200,submitter:'Curated',type:'curated',tags:['docker','devops','ci-cd','kubernetes']},
    {id:17,title:'Unit Test Suite Generator',category:'coding',text:'Generate comprehensive unit tests for: [CODE]. Include: test plan, test setup, happy path tests, edge cases, error handling tests, mocking strategy, complete test suite, coverage report interpretation.',rating:4.8,uses:8700,submitter:'Curated',type:'curated',tags:['testing','unit-tests','tdd','quality-assurance']},
    {id:18,title:'GraphQL Schema Designer',category:'coding',text:'Design GraphQL schema for [APPLICATION]. Include: type definitions, queries, mutations, subscriptions, resolver structure, authentication & authorization, error handling, performance optimization, example queries.',rating:4.7,uses:6300,submitter:'Curated',type:'curated',tags:['graphql','api','backend','schema-design']},
    {id:19,title:'Security Audit Checklist',category:'coding',text:'Conduct security audit for [APPLICATION]. Audit: authentication, authorization, input validation, data protection, API security, dependency security, infrastructure, logging & monitoring, code security. For each vulnerability: severity, remediation steps.',rating:4.9,uses:10100,submitter:'Curated',type:'curated',tags:['security','audit','vulnerability','best-practices']},
    {id:20,title:'Microservices Architecture Design',category:'coding',text:'Design microservices architecture for [SYSTEM]. Include: service decomposition, communication patterns, data management, service discovery, API gateway, deployment strategy, observability, resilience patterns, migration plan.',rating:4.8,uses:7900,submitter:'Curated',type:'curated',tags:['microservices','architecture','distributed-systems']},
    {id:21,title:'Git Workflow & Best Practices',category:'coding',text:'Design Git workflow for [TEAM]. Include: branching strategy, commit conventions, merge strategy, code review process, CI/CD integration, version control, hotfix procedure, documentation, automation.',rating:4.7,uses:8400,submitter:'Curated',type:'curated',tags:['git','version-control','workflow','best-practices']},
    {id:22,title:'Mobile App Performance Optimization',category:'coding',text:'Optimize mobile app performance for [PLATFORM]. Analyze: startup time, memory management, network optimization, UI performance, battery optimization, app size reduction, database optimization, profiling & monitoring.',rating:4.8,uses:6700,submitter:'Curated',type:'curated',tags:['mobile','performance','optimization','ios','android']},

    // WRITING (8 prompts) - IDs 23-30
    {id:23,title:'Professional Email Writer',category:'writing',text:'Write professional email for [SITUATION]. Include: clear subject line, appropriate greeting, concise body (under 200 words), specific action items, appropriate sign-off. Tone: [Formal/Semi-formal/Friendly professional].',rating:4.9,uses:18600,submitter:'Curated',type:'curated',tags:['email','professional','communication','business']},
    {id:24,title:'LinkedIn Post Creator',category:'writing',text:'Create engaging LinkedIn post about [TOPIC]. Include: hook (first 2 lines), body content with insights, engagement elements, hashtags (3-5), CTA. Provide 2 versions: personal/storytelling and data-driven/professional.',rating:4.8,uses:11200,submitter:'Curated',type:'curated',tags:['linkedin','social-media','content','professional']},
    {id:25,title:'Technical Documentation Writer',category:'writing',text:'Create comprehensive technical documentation for [SOFTWARE/FEATURE]. Include: overview, prerequisites, getting started, core concepts, detailed guides with examples, API reference, troubleshooting, best practices.',rating:4.9,uses:9800,submitter:'Curated',type:'curated',tags:['documentation','technical-writing','guides','api-docs']},
    {id:26,title:'Press Release Generator',category:'writing',text:'Write professional press release for [ANNOUNCEMENT]. Include: headline, subheadline, lead paragraph, body (2-3 paragraphs), company boilerplate, contact information. Follow AP Style. 400-600 words.',rating:4.7,uses:5600,submitter:'Curated',type:'curated',tags:['press-release','pr','media','corporate-communications']},
    {id:27,title:'Resume & Cover Letter Optimizer',category:'writing',text:'Optimize resume and cover letter for [JOB]. Include: ATS-friendly formatting, keyword optimization, achievement-focused bullets with quantified results, compelling summary, tailored cover letter (under 400 words).',rating:4.8,uses:14300,submitter:'Curated',type:'curated',tags:['resume','cover-letter','job-search','career']},
    {id:28,title:'Case Study Writer',category:'writing',text:'Write compelling customer case study for [CLIENT/PROJECT]. Include: executive summary, client background, challenge deep-dive, solution details, quantified results, client testimonial, key takeaways, CTA. 1000-1500 words.',rating:4.9,uses:7400,submitter:'Curated',type:'curated',tags:['case-study','content-marketing','success-story','b2b']},
    {id:29,title:'Grant Proposal Writer',category:'writing',text:'Write grant proposal for [PROJECT]. Include: cover letter, executive summary, statement of need, project description with SMART goals, evaluation plan, organizational capacity, detailed budget, sustainability plan.',rating:4.7,uses:4200,submitter:'Curated',type:'curated',tags:['grant-writing','nonprofit','fundraising','proposal']},
    {id:30,title:'Whitepaper Writer',category:'writing',text:'Create authoritative whitepaper on [TOPIC]. Include: executive summary, introduction, background/context, the challenge, solution/approach, technical details, implementation guide, results/benefits, conclusion. 2500-5000 words.',rating:4.8,uses:6900,submitter:'Curated',type:'curated',tags:['whitepaper','content-marketing','b2b','thought-leadership']},

    // BUSINESS (8 prompts) - IDs 31-38
    {id:31,title:'Business Model Canvas Generator',category:'business',text:'Create comprehensive Business Model Canvas for [BUSINESS]. Fill all 9 blocks: customer segments, value propositions, channels, customer relationships, revenue streams, key resources, key activities, key partnerships, cost structure. Include competitive advantages and validation plan.',rating:4.9,uses:13400,submitter:'Curated',type:'curated',tags:['business-model','strategy','startup','planning']},
    {id:32,title:'SWOT Analysis Framework',category:'business',text:'Conduct comprehensive SWOT analysis for [COMPANY/PROJECT]. List 5-10 items per category with evidence. Include SO/WO/ST/WT strategies, priority matrix, action plan with owners and timelines.',rating:4.8,uses:10200,submitter:'Curated',type:'curated',tags:['swot-analysis','strategy','business-planning','analysis']},
    {id:33,title:'Investor Pitch Deck Creator',category:'business',text:'Create compelling investor pitch deck for [COMPANY]. 10-15 slides: cover, problem, solution, market opportunity, product, traction, business model, go-to-market, competitive landscape, team, financial projections, the ask. Include storytelling arc and design principles.',rating:4.9,uses:9800,submitter:'Curated',type:'curated',tags:['pitch-deck','fundraising','investors','startup']},
    {id:34,title:'Marketing Strategy Plan',category:'business',text:'Develop comprehensive marketing strategy for [COMPANY/PRODUCT]. Include: situation analysis, target audience personas, positioning & messaging, channel strategy (content, social, email, paid ads), 90-day action plan, budget breakdown, metrics & KPIs.',rating:4.8,uses:11600,submitter:'Curated',type:'curated',tags:['marketing-strategy','business-planning','growth']},
    {id:35,title:'Competitive Analysis Report',category:'business',text:'Create detailed competitive analysis for [YOUR COMPANY]. Analyze 3-5 competitors: company overview, product/service analysis, positioning & messaging, marketing strategy, customer analysis, strengths & weaknesses, strategic recommendations, monitoring plan.',rating:4.9,uses:8900,submitter:'Curated',type:'curated',tags:['competitive-analysis','market-research','strategy']},
    {id:36,title:'OKR Framework',category:'business',text:'Create OKR framework for [COMPANY/TEAM]. Generate 3-5 objectives with 3-5 key results each. Include: context, cascading structure, initiatives, tracking cadence, scoring rubric, communication plan, common pitfalls to avoid.',rating:4.8,uses:7400,submitter:'Curated',type:'curated',tags:['okr','goal-setting','strategy','performance-management']},
    {id:37,title:'Crisis Management Plan',category:'business',text:'Create comprehensive crisis management plan for [COMPANY]. Include: crisis definition & levels, crisis types & scenarios, crisis management team, communication protocols, action plans, templates, resource inventory, training plan, recovery process.',rating:4.9,uses:5800,submitter:'Curated',type:'curated',tags:['crisis-management','risk-management','business-continuity']},
    {id:38,title:'Customer Journey Mapping',category:'business',text:'Create detailed customer journey map for [PRODUCT/SERVICE]. Map stages: awareness, consideration, purchase, onboarding, usage, expansion. For each: customer actions, touchpoints, thoughts, emotions, pain points, opportunities. Include improvement roadmap.',rating:4.9,uses:8600,submitter:'Curated',type:'curated',tags:['customer-journey','ux','customer-experience','strategy']},

    // PROJECT MANAGEMENT (8 prompts) - IDs 39-46
    {id:39,title:'Project Charter Template',category:'project-management',text:'Create comprehensive project charter for [PROJECT]. Include: executive summary, business case, SMART objectives, scope (in/out), deliverables, milestones & timeline, stakeholders, team & RACI, risks & mitigation, budget, success criteria, governance.',rating:4.9,uses:16700,submitter:'Curated',type:'curated',tags:['project-charter','project-management','pmi','planning']},
    {id:40,title:'Agile Sprint Planning',category:'project-management',text:'Plan effective Agile sprint for [PRODUCT]. Include: sprint goal, capacity planning, user stories with acceptance criteria, story points, definition of ready/done, ceremonies schedule, sprint board, dependencies, success metrics.',rating:4.8,uses:11200,submitter:'Curated',type:'curated',tags:['agile','sprint-planning','scrum','project-management']},
    {id:41,title:'Risk Assessment Matrix',category:'project-management',text:'Conduct comprehensive risk assessment for [PROJECT]. Identify 10+ risks with probability, impact, severity. Include: risk categories, mitigation strategies, contingency plans, monitoring approach, escalation procedures.',rating:4.9,uses:9400,submitter:'Curated',type:'curated',tags:['risk-management','project-management','pmi']},
    {id:42,title:'Stakeholder Management Plan',category:'project-management',text:'Create stakeholder management plan for [PROJECT]. Include: stakeholder identification & analysis, power/interest grid, communication strategy by stakeholder type, engagement tactics, resistance management, RACI matrix.',rating:4.8,uses:7800,submitter:'Curated',type:'curated',tags:['stakeholder-management','project-management','communication']},
    {id:43,title:'Change Management Strategy',category:'project-management',text:'Develop change management strategy for [PROJECT/CHANGE]. Include: change impact assessment, stakeholder analysis, communication plan, training strategy, resistance management, adoption metrics, continuous improvement.',rating:4.7,uses:6900,submitter:'Curated',type:'curated',tags:['change-management','project-management','organizational-change']},
    {id:44,title:'Product Roadmap Generator',category:'project-management',text:'Create product roadmap for [PRODUCT]. Include: vision statement, strategic themes, quarterly goals, feature prioritization (MoSCoW/RICE), release plan, success metrics, stakeholder communication.',rating:4.8,uses:10300,submitter:'Curated',type:'curated',tags:['product-roadmap','product-management','planning']},
    {id:45,title:'Meeting Facilitation Guide',category:'project-management',text:'Create effective meeting structure for [MEETING TYPE]. Include: pre-meeting prep, agenda with timeboxes, facilitation techniques, decision-making framework, action items tracking, follow-up process.',rating:4.6,uses:8700,submitter:'Curated',type:'curated',tags:['meetings','facilitation','productivity','collaboration']},
    {id:46,title:'User Story Writing',category:'project-management',text:'Write effective user stories for [FEATURE/EPIC]. Use proper format (As a/I want/So that), detailed acceptance criteria, story points estimation, technical considerations, dependencies, definition of done.',rating:4.8,uses:9400,submitter:'Curated',type:'curated',tags:['user-stories','agile','scrum','requirements']},

    // DESIGN (8 prompts) - IDs 47-54
    {id:47,title:'UX Research Plan',category:'design',text:'Create comprehensive UX research plan for [PRODUCT/FEATURE]. Include: research objectives, methodology (qualitative/quantitative), participant recruitment, research protocol, analysis plan, timeline, deliverables.',rating:4.9,uses:7100,submitter:'Curated',type:'curated',tags:['ux-research','user-research','design','research-plan']},
    {id:48,title:'Design System Documentation',category:'design',text:'Document comprehensive design system for [PRODUCT/BRAND]. Include: brand foundations (colors, typography, spacing), component library, patterns, usage guidelines, accessibility standards, code examples.',rating:4.8,uses:6400,submitter:'Curated',type:'curated',tags:['design-system','documentation','ui-design','brand-guidelines']},
    {id:49,title:'User Persona Creator',category:'design',text:'Create detailed user personas for [PRODUCT]. Include: demographics, behaviors, goals, pain points, motivations, user journey, tech-savviness, design implications. Create 2-3 personas.',rating:4.7,uses:8700,submitter:'Curated',type:'curated',tags:['personas','user-research','ux','design']},
    {id:50,title:'Wireframe & Prototype Guide',category:'design',text:'Create wireframes and prototypes for [FEATURE/APP]. Include: information architecture, user flows, wireframes (low/high fidelity), interaction specifications, responsive design considerations.',rating:4.8,uses:7900,submitter:'Curated',type:'curated',tags:['wireframing','prototyping','ux-design','product-design']},
    {id:51,title:'Accessibility Audit',category:'design',text:'Conduct accessibility audit for [WEBSITE/APP]. Check WCAG 2.1 AA compliance: perceivable, operable, understandable, robust. Include: issues list with severity, recommendations, remediation plan, testing tools.',rating:4.9,uses:5200,submitter:'Curated',type:'curated',tags:['accessibility','a11y','wcag','inclusive-design']},
    {id:52,title:'Design Critique Framework',category:'design',text:'Provide constructive design critique for [DESIGN/INTERFACE]. Analyze: visual hierarchy, usability, accessibility, consistency, brand alignment, mobile responsiveness. Provide specific, actionable feedback.',rating:4.7,uses:6800,submitter:'Curated',type:'curated',tags:['design-critique','design-review','feedback','ui-ux']},
    {id:53,title:'Information Architecture',category:'design',text:'Design information architecture for [WEBSITE/APP]. Include: content inventory, sitemap, navigation structure, taxonomy, labeling system, search strategy, card sorting results.',rating:4.8,uses:5900,submitter:'Curated',type:'curated',tags:['information-architecture','ia','ux','content-strategy']},
    {id:54,title:'Mobile App Design Guide',category:'design',text:'Design mobile app for [PURPOSE/AUDIENCE]. Include: UX strategy, screen flows, UI components, gestures & interactions, iOS/Android platform guidelines, accessibility, performance considerations.',rating:4.9,uses:8100,submitter:'Curated',type:'curated',tags:['mobile-design','app-design','ios','android','ui-ux']},

    // EDUCATION (6 prompts) - IDs 55-60
    {id:55,title:'Course Curriculum Designer',category:'education',text:'Design comprehensive course curriculum for [SUBJECT]. Include: learning outcomes (4-6), course structure (modules/lessons), teaching methods, assessment strategy (formative/summative), resources & materials, schedule, success metrics.',rating:4.8,uses:5600,submitter:'Curated',type:'curated',tags:['education','curriculum','course-design','teaching']},
    {id:56,title:'Lesson Plan Generator',category:'education',text:'Create detailed lesson plans for [TOPIC/GRADE LEVEL]. Include: learning objectives, warm-up, instruction, guided practice, independent practice, assessment, differentiation strategies, materials needed, timing.',rating:4.7,uses:8900,submitter:'Curated',type:'curated',tags:['lesson-planning','teaching','education','pedagogy']},
    {id:57,title:'Educational Assessment Creator',category:'education',text:'Design comprehensive assessments for [SUBJECT/LEARNING OBJECTIVES]. Include: question types (multiple choice, short answer, essay), rubrics, answer keys, alignment with learning outcomes, differentiation.',rating:4.8,uses:6300,submitter:'Curated',type:'curated',tags:['assessment','testing','education','evaluation']},
    {id:58,title:'Student Feedback Generator',category:'education',text:'Generate constructive student feedback for [ASSIGNMENT/PERFORMANCE]. Include: strengths with specific examples, areas for improvement, actionable next steps, encouragement, growth mindset language.',rating:4.6,uses:7200,submitter:'Curated',type:'curated',tags:['feedback','teaching','education','student-assessment']},
    {id:59,title:'Training Program Development',category:'education',text:'Develop comprehensive training program for [SKILL/TOPIC]. Include: needs analysis, learning objectives, curriculum structure, delivery methods, practice activities, assessment & evaluation, materials.',rating:4.9,uses:5800,submitter:'Curated',type:'curated',tags:['training','professional-development','education']},
    {id:60,title:'Learning Path Designer',category:'education',text:'Create personalized learning path for [SKILL/CAREER GOAL]. Include: current skill assessment, prerequisite skills, recommended courses, projects, resources, time estimates, milestones, certification options.',rating:4.7,uses:6900,submitter:'Curated',type:'curated',tags:['learning-path','education','career-development']},

    // DATA SCIENCE (6 prompts) - IDs 61-66
    {id:61,title:'Data Analysis Project Plan',category:'data-science',text:'Create data analysis project plan for [BUSINESS QUESTION]. Include: problem definition, data requirements, EDA approach, analysis methods, visualization strategy, insights framework, deliverables, timeline.',rating:4.8,uses:5900,submitter:'Curated',type:'curated',tags:['data-analysis','data-science','analytics']},
    {id:62,title:'Machine Learning Model Development',category:'data-science',text:'Develop ML model for [PREDICTION/CLASSIFICATION TASK]. Include: data preprocessing, feature engineering, model selection, training approach, evaluation metrics, hyperparameter tuning, deployment strategy.',rating:4.9,uses:7200,submitter:'Curated',type:'curated',tags:['machine-learning','data-science','predictive-modeling']},
    {id:63,title:'Data Visualization Dashboard',category:'data-science',text:'Design data visualization dashboard for [BUSINESS METRICS]. Include: chart selection rationale, layout design, color palette, interactivity features, filters, drill-down capabilities, storytelling approach.',rating:4.7,uses:6100,submitter:'Curated',type:'curated',tags:['data-visualization','dashboards','business-intelligence']},
    {id:64,title:'A/B Test Design & Analysis',category:'data-science',text:'Design and analyze A/B test for [FEATURE/CHANGE]. Include: hypothesis, sample size calculation, statistical test selection, randomization approach, success metrics, analysis plan, results interpretation.',rating:4.9,uses:7800,submitter:'Curated',type:'curated',tags:['ab-testing','statistics','experimentation']},
    {id:65,title:'Predictive Analytics Framework',category:'data-science',text:'Build predictive analytics framework for [BUSINESS PROBLEM]. Include: data pipeline design, feature engineering, model development, validation strategy, monitoring & retraining, business integration.',rating:4.8,uses:6700,submitter:'Curated',type:'curated',tags:['predictive-analytics','forecasting','machine-learning']},
    {id:66,title:'SQL Data Extraction',category:'data-science',text:'Create optimized SQL queries for [DATA EXTRACTION TASK]. Include: query structure, joins, aggregations, window functions, CTEs, performance optimization, indexing recommendations, error handling.',rating:4.8,uses:8400,submitter:'Curated',type:'curated',tags:['sql','data-engineering','database']},

    // BONUS PROMPTS (4 prompts) - IDs 67-70
    {id:67,title:'Newsletter Content Strategy',category:'marketing',text:'Develop newsletter content strategy for [AUDIENCE/BUSINESS]. Include: content pillars, editorial calendar, subject line formulas, templates, engagement tactics, growth strategies, metrics to track.',rating:4.7,uses:6700,submitter:'Curated',type:'curated',tags:['newsletter','email-marketing','content-strategy']},
    {id:68,title:'Competitive Pricing Strategy',category:'business',text:'Develop pricing strategy for [PRODUCT/SERVICE]. Include: pricing models comparison, competitor analysis, value-based pricing approach, price anchoring, tiering structure, testing approach, implementation plan.',rating:4.9,uses:6900,submitter:'Curated',type:'curated',tags:['pricing','strategy','business','revenue']},
    {id:69,title:'Code Documentation Generator',category:'coding',text:'Generate comprehensive code documentation for [CODEBASE/PROJECT]. Include: README with setup, API documentation, inline comments, architecture diagrams, contribution guidelines, troubleshooting guide.',rating:4.7,uses:8300,submitter:'Curated',type:'curated',tags:['documentation','coding','readme','technical-writing']},
    {id:70,title:'Customer Support Response Templates',category:'writing',text:'Create customer support response templates for [COMMON SCENARIOS]. Include: empathetic opening, clear solution steps, alternative options, escalation paths, satisfaction follow-up, brand voice consistency.',rating:4.8,uses:7700,submitter:'Curated',type:'curated',tags:['customer-support','templates','communication']}
];
